### ISSUE TITLE
#INC-5312: Missing image

### ISSUE THREAD

**Issue by vanessa-cooper** [ObelusFamily/Anythink-Market-l1crwxrj#1]
It seems that when creating a new product without an image, there are broken images showing up in the product catalog. Please fix this by replicating this bug locally with mock data. Take a screenshot of the fix and attach it to a PR when you close the bug. There's a placeholder image in the repo that you can use named `placeholder.png`

**Comment by Leith42** [comment]
![image](https://user-images.githubusercontent.com/20539674/205380685-2b1fb695-57e8-44b3-8712-6ee5824e8040.png)

**Comment by Leith42** [comment]
Fixed in #2
